//go:build podman

package main

import (
	"os"
	"path/filepath"
)

// minimalRegistriesConf is a minimal, always-valid (v2-format) registries.conf.
//
// go.podman.io/image (the containers/image-descended library the podman
// backend links against, see backend_podman.go) hard-refuses to load a
// v1-format registries.conf at all — no fallback, no defaults, every
// registry operation (pull/push/inspect/transfer, even login) just fails
// outright. Some real systems still ship one in that legacy format —
// confirmed on every GitHub-hosted ubuntu-24.04[-arm] CI runner as of this
// writing, which is what surfaced this in the first place (the podman e2e
// job's very first run, against a real registry pull, failed with exactly
// this: "registries.conf must be in v2 format but is in v1").
//
// llmman itself never actually needs anything a registries.conf configures
// (mirrors, unqualified-search-registries rewriting, insecure registries,
// ...) — every reference reaching this backend is already fully qualified
// by the time it gets here (see shortnames.rs's own resolution on the Rust
// side, before ffi::pull/push/etc. is ever called) — so this intentionally
// configures nothing. It just needs to *be* valid v2 TOML, so loading it
// always succeeds regardless of whatever the host's own file (if any)
// looks like.
const minimalRegistriesConf = `# Minimal, valid (v2-format) registries.conf, generated by llmman itself
# for its own podman backend — see go-shim/registries_podman.go's own doc
# comment for why this exists instead of using the host's
# /etc/containers/registries.conf.
#
# Set CONTAINERS_REGISTRIES_CONF yourself (see containers-registries.conf(5))
# if you want custom mirrors/search registries/etc: llmman will not
# overwrite, or override, an explicitly-set value of that variable.
unqualified-search-registries = []
`

// ensureRegistriesConf points CONTAINERS_REGISTRIES_CONF at llmman's own
// minimalRegistriesConf, unless the user has already set that variable
// themselves (respected, never overwritten — see minimalRegistriesConf's
// own doc comment). go.podman.io/image's sysregistriesv2 package reads
// this env var itself for every SystemContext that doesn't explicitly set
// SystemRegistriesConfPath — which is every SystemContext this backend
// constructs (see backend_podman.go) — so setting it once here, before
// any of them run, is enough; no call site needs to change.
//
// Best-effort: if this fails for any reason (no home directory, an
// unwritable filesystem, ...), it silently leaves CONTAINERS_REGISTRIES_CONF
// unset, falling back to this process's pre-existing behavior of trusting
// the host's own registries.conf, rather than turning a failure to set up
// this one safeguard into a hard failure of every registry operation.
func ensureRegistriesConf() {
	if os.Getenv("CONTAINERS_REGISTRIES_CONF") != "" {
		return
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	// ~/.local/share/llmman — same directory the Rust side already uses
	// for serve.log (see daemon.rs / the CI workflow's own "Show llmman
	// serve.log" step), not a podman-specific location: this file is
	// llmman's own generated default, unrelated to any real podman/
	// skopeo installation's own config.
	dir := filepath.Join(home, ".local", "share", "llmman")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	path := filepath.Join(dir, "registries.conf")
	// Only write if missing: never clobber a file that already exists,
	// e.g. one a user has since hand-edited to add their own mirrors.
	if _, err := os.Stat(path); os.IsNotExist(err) {
		if err := os.WriteFile(path, []byte(minimalRegistriesConf), 0o644); err != nil {
			return
		}
	}
	os.Setenv("CONTAINERS_REGISTRIES_CONF", path)
}

func init() {
	ensureRegistriesConf()
}
